name: list_all_videos
description: This package is a convenient and efficient tool for Flutter developers looking to list all video file paths stored in a user's local storage. 
version: 1.0.3
homepage: https://www.linkedin.com/in/weviavek/
repository: https://github.com/weviavek/list_all_videos.git

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  permission_handler: ^11.0.0
  path_provider: ^2.1.1
  device_info_plus: ^9.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

platforms:
  android: