name: list_all_videos
description: The list_all_videos package is an indispensable resource for Flutter developers who want to efficiently retrieve video file paths from a user's local storage. This package is expertly designed to seamlessly operate on Android devices, with compatibility extending up to version 14. 
version: 1.0.5
homepage: https://www.linkedin.com/in/weviavek/
repository: https://github.com/weviavek/list_all_videos.git


environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  permission_handler: ^11.0.0
  path_provider: ^2.1.1
  device_info_plus: ^9.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
supported:
  - android
  - ios